proca/lib/proca_web/eci_router.ex
defmodule ProcaWeb.EciRouter do
  @moduledoc """
  Alternative router used in ECI build. Minimal version of ProcaWeb.Router
  """
  use ProcaWeb, :router

  pipeline :api do
    plug :accepts, ["json"]
    plug CORSPlug
    plug ProcaWeb.Plugs.HeadersPlug, ["referer"]
    plug ProcaWeb.Plugs.BlockIntrospectionPlug
    plug ProcaWeb.Plugs.ParseExtensions, schema: %{captcha: :string, captcha_service: :string}
  end

  pipeline :auth_api do
    plug ProcaWeb.Plugs.BasicAuthPlug
  end

  scope "/api" do
    pipe_through :api

    forward "/", Absinthe.Plug, schema: ProcaWeb.Schema.EciSchema
  end

  scope "/private/api" do
    pipe_through :api
    pipe_through :auth_api
    forward "/", ProcaWeb.PrivateAbsinthePlug, schema: ProcaWeb.Schema
  end

  # forward "/graphiql", Absinthe.Plug.GraphiQL,
  #   schema: ProcaWeb.Schema.EciSchema,
  #   interface: :playground,
  #   default_url: "/api"
end

proca/lib/proca_web/router.ex
defmodule ProcaWeb.Router do
  @moduledoc """
  Main app router
  """
  use ProcaWeb, :router

  import ProcaWeb.UserAuth
  # import Phoenix.LiveView.Router

  def allow_origin, do: Application.get_env(:proca, ProcaWeb.Endpoint)[:allow_origin]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    # plug :fetch_live_flash # This is for LiveView
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug :put_root_layout, {ProcaWeb.LayoutView, :root}
  end

  pipeline :api do
    # Support current logged in user
    plug :fetch_session
    plug :fetch_current_user

    plug :accepts, ["json"]
    plug CORSPlug
    plug ProcaWeb.Plugs.HeadersPlug, ["referer"]
    plug ProcaWeb.Plugs.BasicAuthPlug
    plug ProcaWeb.Plugs.TokenAuthPlug
    plug ProcaWeb.Plugs.JwtAuthPlug
  end

  pipeline :api_without_auth do
    plug :accepts, ["json"]
    plug CORSPlug
    plug ProcaWeb.Plugs.HeadersPlug, ["referer"]
  end

  # unused currently, might be useful for /console
  pipeline :auth do
    plug ProcaWeb.Plugs.JwtAuthPlug, query_param: "jwt", enable_session: true
    :require_authenticated_user
  end

  scope "/" do
    pipe_through :browser

    get "/", ProcaWeb.HomepageController, :index
  end

  scope "/link" do
    pipe_through [:api]

    get "/s/:action_id/:verb/:ref", ProcaWeb.ConfirmController, :supporter
    get "/d/:action_id/:ref", ProcaWeb.ConfirmController, :double_opt_in
    get "/:verb/:code", ProcaWeb.ConfirmController, :confirm
    # get "/a/:action_id/:ref/:verb/:code", ProcaWeb.ConfirmController, :confirm_code
  end

  scope "/webhook" do
    pipe_through :api_without_auth

    post "/mailjet", ProcaWeb.WebhookController, :mailjet
  end

  scope "/api" do
    pipe_through :api

    forward "/", Absinthe.Plug,
      schema: ProcaWeb.Schema,
      socket: ProcaWeb.UserSocket
  end

  forward "/graphiql", Absinthe.Plug.GraphiQL,
    schema: ProcaWeb.Schema,
    socket: ProcaWeb.UserSocket,
    interface: :playground,
    default_url: "/api"

  ## Authentication routes

  scope "/", ProcaWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", ProcaWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", ProcaWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

proca/lib/proca_web/controllers/user_reset_password_controller.ex
defmodule ProcaWeb.UserResetPasswordController do
  use ProcaWeb, :controller
  plug :put_layout, "entry.html"

  alias Proca.Users

  plug :get_user_by_reset_password_token when action in [:edit, :update]

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{"user" => %{"email" => email}}) do
    if user = Users.get_user_by_email(email) do
      Users.deliver_user_reset_password_instructions(
        user,
        &Routes.user_reset_password_url(conn, :edit, &1)
      )
    end

    # Regardless of the outcome, show an impartial success/error message.
    conn
    |> put_flash(
      :info,
      "If your email is in our system, you will receive instructions to reset your password shortly."
    )
    |> redirect(to: "/")
  end

  def edit(conn, _params) do
    render(conn, "edit.html", changeset: Users.change_user_password(conn.assigns.user))
  end

  # Do not log in the user after reset password to avoid a
  # leaked token giving the user access to the account.
  def update(conn, %{"user" => user_params}) do
    case Users.reset_user_password(conn.assigns.user, user_params) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Password reset successfully.")
        |> redirect(to: Routes.user_session_path(conn, :new))

      {:error, changeset} ->
        render(conn, "edit.html", changeset: changeset)
    end
  end

  defp get_user_by_reset_password_token(conn, _opts) do
    %{"token" => token} = conn.params

    if user = Users.get_user_by_reset_password_token(token) do
      conn |> assign(:user, user) |> assign(:token, token)
    else
      conn
      |> put_flash(:error, "Reset password link is invalid or it has expired.")
      |> redirect(to: "/")
      |> halt()
    end
  end
end

proca/lib/proca_web/views/user_reset_password_view.ex
defmodule ProcaWeb.UserResetPasswordView do
  use ProcaWeb, :view
end

proca/lib/proca_web/templates/user_reset_password/edit.html.eex
<h1 class="text-2xl leading-relaxed mb-2">Reset password</h1>

<%= form_for @changeset, Routes.user_reset_password_path(@conn, :update, @token), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="input-wrap">
    <span>
      <i class="fas fa-lock"></i>
    </span>

    <%= password_input f, :password, required: true, placeholder: "New password" %>
  </div>
  <%= error_tag f, :password %>

  <div class="input-wrap">
    <span>
      <i class="fas fa-lock"></i>
    </span>
    <%= password_input f, :password_confirmation, required: true, placeholder: "Confirm new password" %>
  </div>
  <%= error_tag f, :password_confirmation %>

  <div>
    <%= submit "Reset password", class: "btn bg-primary my-2" %>
  </div>
<% end %>

<p>
  <%= link "Register", to: Routes.user_registration_path(@conn, :new) %> |
  <%= link "Log in", to: Routes.user_session_path(@conn, :new) %>
</p>

proca/lib/proca_web/templates/user_reset_password/new.html.eex
<h1 class="text-2xl leading-relaxed mb-2">Forgot your password?</h1>

<%= form_for :user, Routes.user_reset_password_path(@conn, :create), fn f -> %>
  <div class="input-wrap">
    <span>
      <i class="fas fa-user"></i>
    </span>
    <%= email_input f, :email, required: true, placeholder: "Email" %>
  </div>
  <%= error_tag f, :email %>

  <div>
    <%= submit "Send instructions to reset password", class: "btn bg-secondary my-2" %>
  </div>
<% end %>

<p>
  <%= link "Register", to: Routes.user_registration_path(@conn, :new) %> |
  <%= link "Log in", to: Routes.user_session_path(@conn, :new) %>
</p>