proca/lib/proca_web/eci_router.ex
defmodule ProcaWeb.EciRouter do
  @moduledoc """
  Alternative router used in ECI build. Minimal version of ProcaWeb.Router
  """
  use ProcaWeb, :router

  pipeline :api do
    plug :accepts, ["json"]
    plug CORSPlug
    plug ProcaWeb.Plugs.HeadersPlug, ["referer"]
    plug ProcaWeb.Plugs.BlockIntrospectionPlug
    plug ProcaWeb.Plugs.ParseExtensions, schema: %{captcha: :string, captcha_service: :string}
  end

  pipeline :auth_api do
    plug ProcaWeb.Plugs.BasicAuthPlug
  end

  scope "/api" do
    pipe_through :api

    forward "/", Absinthe.Plug, schema: ProcaWeb.Schema.EciSchema
  end

  scope "/private/api" do
    pipe_through :api
    pipe_through :auth_api
    forward "/", ProcaWeb.PrivateAbsinthePlug, schema: ProcaWeb.Schema
  end

  # forward "/graphiql", Absinthe.Plug.GraphiQL,
  #   schema: ProcaWeb.Schema.EciSchema,
  #   interface: :playground,
  #   default_url: "/api"
end

proca/lib/proca_web/router.ex
defmodule ProcaWeb.Router do
  @moduledoc """
  Main app router
  """
  use ProcaWeb, :router

  import ProcaWeb.UserAuth
  # import Phoenix.LiveView.Router

  def allow_origin, do: Application.get_env(:proca, ProcaWeb.Endpoint)[:allow_origin]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    # plug :fetch_live_flash # This is for LiveView
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug :put_root_layout, {ProcaWeb.LayoutView, :root}
  end

  pipeline :api do
    # Support current logged in user
    plug :fetch_session
    plug :fetch_current_user

    plug :accepts, ["json"]
    plug CORSPlug
    plug ProcaWeb.Plugs.HeadersPlug, ["referer"]
    plug ProcaWeb.Plugs.BasicAuthPlug
    plug ProcaWeb.Plugs.TokenAuthPlug
    plug ProcaWeb.Plugs.JwtAuthPlug
  end

  pipeline :api_without_auth do
    plug :accepts, ["json"]
    plug CORSPlug
    plug ProcaWeb.Plugs.HeadersPlug, ["referer"]
  end

  # unused currently, might be useful for /console
  pipeline :auth do
    plug ProcaWeb.Plugs.JwtAuthPlug, query_param: "jwt", enable_session: true
    :require_authenticated_user
  end

  scope "/" do
    pipe_through :browser

    get "/", ProcaWeb.HomepageController, :index
  end

  scope "/link" do
    pipe_through [:api]

    get "/s/:action_id/:verb/:ref", ProcaWeb.ConfirmController, :supporter
    get "/d/:action_id/:ref", ProcaWeb.ConfirmController, :double_opt_in
    get "/:verb/:code", ProcaWeb.ConfirmController, :confirm
    # get "/a/:action_id/:ref/:verb/:code", ProcaWeb.ConfirmController, :confirm_code
  end

  scope "/webhook" do
    pipe_through :api_without_auth

    post "/mailjet", ProcaWeb.WebhookController, :mailjet
  end

  scope "/api" do
    pipe_through :api

    forward "/", Absinthe.Plug,
      schema: ProcaWeb.Schema,
      socket: ProcaWeb.UserSocket
  end

  forward "/graphiql", Absinthe.Plug.GraphiQL,
    schema: ProcaWeb.Schema,
    socket: ProcaWeb.UserSocket,
    interface: :playground,
    default_url: "/api"

  ## Authentication routes

  scope "/", ProcaWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", ProcaWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", ProcaWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

proca/lib/proca_web/views/layout_view.ex
defmodule ProcaWeb.LayoutView do
  use ProcaWeb, :view
  alias ProcaWeb.UserAuth

  def gravatar_url(nil) do
    "//gravatar.com/avatar/default"
  end

  def gravatar_url(user) do
    h =
      :crypto.hash(:md5, user.email)
      |> Base.encode16()
      |> String.downcase()

    "//gravatar.com/avatar/" <> h
  end
end

proca/lib/proca_web/templates/layout/_stars.html.eex
<!-- https://www.script-tutorials.com/night-sky-with-twinkling-stars/ -->
<div class="stars"></div>
<div class="twinkling"></div>

proca/lib/proca_web/templates/layout/_user_menu.html.eex
<nav class="bg-gradient-to-r from-primary to-secondary relative z-10">
  <!-- big bar -->
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <!-- make left and right side, and height -->
    <div class="relative flex items-center justify-between h-16 z-10">
      <div class="flex-1 flex items-center justify-start">
        <!-- logo -->
        <div class="h-10 w-10 rounded-full border-2 border-gray-300 mr-10">
          <a href="/">
          <img class="h-full w-full mx-auto"
            src="<%= Routes.static_path(@conn, "/images/proca-logo.png") %>" 
            alt="Proca logo" />
          </a>
        </div>
        <div class="flex space-x-4">
        <%= if UserAuth.auth_enabled?(:local) do %>
        <% btn_class="btn bg-logo-gray" %>
        <%= if @user do %>
        <%= link "Settings", to: Routes.user_settings_path(@conn, :edit), class: btn_class %>
        <%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete, class: btn_class %>
        <% else %>
        <%= link "Register", to: Routes.user_registration_path(@conn, :new), class: btn_class %>
        <%= link "Log in", to: Routes.user_session_path(@conn, :new), class: btn_class %>
        <% end %>
        <% end %>

        <%= if UserAuth.auth_enabled?(:sso) do %>
        <% btn_class="btn bg-logo-gray" %>
        <%= if is_nil @user do %>
        <%= link "Single Sign On", to: UserAuth.sso_url(@conn), class: btn_class %>
        <% end %>
        <% end %>
        
        </div>

      </div>      
      <div class="absolute inset-y-0 right-0 flex items-center pr-2">
      <%= if @user do %>
        <img class="h-10 w-10 rounded-full border-2 border-gray-300 " src="<%= gravatar_url(@user) %>" alt="">
      <% end %>
      </div>
    </div>
  </div>

</nav>

proca/lib/proca_web/templates/layout/app.html.eex
<!-- Falsh msg (should be live view b/c what about live alerts? -->
<div id="flash" class="container m-auto">
  <%= if get_flash(@conn, :info) do %>
    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <% end %>

  <%= if get_flash(@conn, :error) do %>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <% end %>
</div>
<!-- End Flash msg -->


<div class="container mt-3 flex flex-col items-center">
  <%= @inner_content %>
</article>

</div>

proca/lib/proca_web/templates/layout/entry.html.eex
<div class="container lg:mt-5 m-auto h-full flex flex-col justify-itemx-center">
  <!-- gray window -->
  <article class="lg:m-7 p-2  lg:m-auto lg:w-1/3 bg-purple-50 bg-opacity-85 lg:rounded-xl">
    <div class="container flex flex-col items-center p-4">
      <%= @inner_content %>
    </div>
  </article>
</div>

proca/lib/proca_web/templates/layout/root.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= assigns[:page_title] || "Proca" %></title>

    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/fontawesome/all.min.css") %>">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/assets/app.css") %>"/>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/stars.css") %>"/>

    <%= csrf_meta_tag() %>
  </head>


  <body>
    <%= render "_user_menu.html", assigns %>

    <div class="w-screen block">
      <%= @inner_content %>
    </div> 

    <%= render "_stars.html", assigns %>

    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/assets/app.js") %>"></script>
  </body>
</html>